# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: xtrymind blog
email: xtrymind@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  another version of xtrymind random writing~
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xtrymind.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xtrymind
github_username:  xtrymind

disqus:
  shortname: xtrymind-github-io

permalink: "/:title/"
author:
  name: Dede Dindin Qudsy
  uri: http://xtrymind.github.io/
  email: xtrymind@gmail.com
  google-plus: +DedeDindinQudsy
  github: xtrymind
  twitter: xtrymind
  instagram: xtrymind

twitter:
  username: xtrymind

social:
  name: Dede Dindin Qudsy
  links:
    - https://twitter.com/xtrymind
    - https://plus.google.com/+DedeDindinQudsy
    - https://github.com/xtrymind

# Build settings
markdown: kramdown
tag_page_layout: tag_page
tag_page_dir: tag
timezone: Asia/Jakarta

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
