# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
name: xtrymind
title: xtrymind blog
email: xtrymind@gmail.com

author:
  name: Dede Dindin Qudsy
  uri: http://xtrymind.github.io/
  email: xtrymind@gmail.com
  google-plus: +xtrymind
  github: xtrymind
  twitter: xtrymind
  instagram: xtrymind


description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Publishing settings
permalink: /:title/

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
